apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craft
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aleksandrakojic/microservices-on-k8s
    targetRevision: argo-dev
    path: microservices-on-k8s/k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: craft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true